import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import {
  INTERVALS,
  type Interval,
  windowFileBasename,
  windowStartsForInterval,
} from '../src/config/intervals.ts';

const OUT_PATH = join('src', 'config', 'start-dates.generated.ts');

function emitTuple(interval: Interval): string {
  const dates = windowStartsForInterval(interval).map(windowFileBasename);
  const lines = dates.map((d) => `  '${d}',`).join('\n');
  return `export const START_DATES_${interval} = [\n${lines}\n] as const;\n\nexport type StartDate_${interval} = (typeof START_DATES_${interval})[number];\n`;
}

const body = `// AUTO-GENERATED by scripts/generate-start-dates.ts. Do not edit by hand.\n// Run \`npm run generate:start-dates\` to regenerate.\n\n${INTERVALS.map(emitTuple).join('\n')}
export const START_DATES = {
${INTERVALS.map((i) => `  '${i}': START_DATES_${i},`).join('\n')}
} as const;
`;

await writeFile(OUT_PATH, body, 'utf8');
console.log(`Wrote ${OUT_PATH}`);
